### ISSUE TITLE
Inserção duplicada nas disciplinas do PTD

### ISSUE THREAD

**Issue by davidalain** [ifpe-cti/DEN#7]
@vsnepomuceno  Ao fazer o cadastro de disciplinas no PTD, o sistema está inserindo ou mostrando as disciplinas de maneira duplicada.
![ptd_erro](https://cloud.githubusercontent.com/assets/5804008/15378870/b3ac7100-1d3d-11e6-8cda-0431a686534d.jpg)

O problema também ocorre no campo **ATIVIDADES DE APOIO AO ENSINO**.

**Comment by vsnepomuceno** [comment]
Resolvida!
